# Collector specific configuration
base_url: "ftp://ftp.uis.unesco.org/BDDS"
indicatorsetcodes:
  NATMON:
    title: "National Monitoring"
    showcase: "http://uis.unesco.org/#tabs-themes_tab-center-1"
    quickcharts:
      - code: "GER.1t3"
        title: "Gross enrolment ratio, primary and secondary"
        unit: "Percentage (%)"
      - code: "XGDP.1.FSgov"
        title: "Government expenditure on primary education"
        unit: "Percentage of GDP (%)"
      - code: "XGDP.2.FSgov"
        title: "Government expenditure on lower secondary education"
        unit: "Percentage of GDP (%)"
  SDG:
    title: "SDG 4 Global and Thematic"
    showcase: "http://uis.unesco.org/en/topic/sustainable-development-goal-4"
  DEM:
    title: "Demographic and Socio-economic"
    showcase: " "
