# Collector specific configuration
base_url: "ftp://ftp.uis.unesco.org/BDDS"
indicatorsetcodes:
  NATMON:
    title: "National Monitoring"
    showcase: "http://uis.unesco.org/#tabs-themes_tab-center-1"
    quickcharts:
      - code: "GER.1T8"
        title: "Gross enrolment ratio, primary to tertiary, both sexes (%)"
        unit: "Percentage (%)"
      - code: "SLE.1T8.GPI"
        title: "School life expectancy, primary to tertiary, gender parity index (GPI)"
        unit: "Index (0 to 1)"
      - code: "FTP.2T3"
        title: "Percentage of teachers in secondary education who are female"
        unit: "Percentage (%)"
  SDG:
    title: "SDG 4 Global and Thematic"
    showcase: "http://uis.unesco.org/en/topic/sustainable-development-goal-4"
  DEM:
    title: "Demographic and Socio-economic"
    showcase: " "
