# Collector specific configuration
base_url: "ftp://ftp.uis.unesco.org/BDDS"
indicatorsetcodes:
  EDUN:
    title: "Students and Teachers"
    showcase: "http://uis.unesco.org/#tabs-themes_tab-center-1"
    quickcharts:
      - "20082"
      - "20122"
      - "26375"
  EDUF:
    title: "Education Expenditure and Funding"
    showcase: "http://uis.unesco.org/en/topic/education-finance"
#    quickcharts:
#      - "20154"
#      - "20173"
#      - "901069"
  EDUR:
    title: "School Resources and Teaching Conditions in Africa"
    showcase: "http://uis.unesco.org/en/topic/education-africa"
#    quickcharts:
#      - "20154"
#      - "20173"
#      - "901069"
  SDG:
    title: "SDG 4 Global and Thematic Indicators"
    showcase: "http://uis.unesco.org/en/topic/sustainable-development-goal-4"
#    quickcharts:
#      - "EA.7t8.Ag25t99"
#      - "XUNIT.GDPcap.2t3.Fsgov.FFntr"
#      - "yadult.profiliteracy"
  DEM:
    title: "Demographic and Socio-economic Indicators"
    showcase: " "
#    quickcharts:
#      - "200101"
#      - "ILO.EMP.MF.15+.000"
#      - "NY.GDP.PCAP.CD"

