# Collector specific configuration
indicatorsetcodes:
  SDG:
    title: "SDG 4 Global and Thematic"
    showcase: "https://uis.unesco.org/en/topic/sustainable-development-goal-4"
  OPRI:
    title: "Other Policy Relevant Indicators"
    showcase: "https://uis.unesco.org/#tabs-themes_tab-center-1"
  DEM:
    title: "Demographic and Socio-economic"
    showcase: " "
